# Generated by Django 3.1.2 on 2020-10-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='genero',
            new_name='marca',
        ),
    ]
