# Generated by Django 3.1.2 on 2020-10-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201027_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Marca',
        ),
    ]
